-- !Ups
CREATE TABLE PAYMENT (
    ADDRESS VARCHAR(255) NOT NULL PRIMARY KEY,
    AMOUNT BIGINT NOT NULL,
    TXID   VARCHAR(255) not null,
    CHECK (("AMOUNT" >= 0))
);

-- !Downs
DROP TABLE PAYMENT;
