-- !Ups
CREATE TABLE TOKEN_PAYMENT (
    ADDRESS VARCHAR(255) NOT NULL,
    ERG_AMOUNT BIGINT NOT NULL,
    TYPE_TOKENS   VARCHAR(255) not null,
    TXID   VARCHAR(255) not null,
    CHECK (("ERG_AMOUNT" >= 0)),
    PRIMARY KEY (ADDRESS, TYPE_TOKENS)
);

-- !Downs
DROP TABLE TOKEN_PAYMENT;
