-- !Ups
ALTER TABLE TOKEN_PAYMENT ADD IP VARCHAR(100) DEFAULT null;
ALTER TABLE TOKEN_PAYMENT_ARCHIVE ADD IP VARCHAR(100) DEFAULT null;

-- !Downs
ALTER TABLE TOKEN_PAYMENT DROP IP;
ALTER TABLE TOKEN_PAYMENT_ARCHIVE DROP IP;
